# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenWeatherMap

  pod 'Alamofire'
  pod 'SGImageCache'

  target 'OpenWeatherMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenWeatherMapUITests' do
    # Pods for testing
  end

end
